import type { Metadata } from "next";
import Navigation from "@/components/Navigation/Navigation";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full" suppressHydrationWarning>
      <body
        className={`bg-blue-500 flex flex-col h-full`}
      >
        <div className="container mx-auto flex flex-col justify-between h-full">
          {children}
          <Navigation />
        </div>
      </body>
    </html>
  );
}
