import type { Metadata } from "next";
import Navigation from "@/components/Navigation/Navigation";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`bg-blue-500 flex flex-col h-full`}
      >
        <div className="container mx-auto flex flex-col justify-between h-full">
          {children}
          <Navigation />
        </div>
      </body>
    </html>
  );
}
